apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-pvc
spec:
  accessModes:
    - ReadWriteOnce            # or ReadWriteMany if supported
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard 

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: model-trainer-job
spec:
  # Every 2 minutes (minute field */2). Use "* * * * *" for every minute.
  schedule: "*/2 * * * *"
  concurrencyPolicy: Forbid  # Don't start new job if previous still running
  successfulJobsHistoryLimit: 5         # keep only 5 (keep disk util low)
  failedJobsHistoryLimit: 5             # keep no more than 5 (keep disk util low)    
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 600       # delete Job 10 minutes after it finishes
      template:
        metadata:
          labels:
            app: model-trainer
        spec:
          containers:
          - name: model-trainer
            # Replace <DockerHub-Username> with your Docker Hub username (see README "Build and Push the Docker Image").
            # Example: docker build -t janedoe/mlip-model-trainer:1.0.0 -f Dockerfile.trainer . && docker push janedoe/mlip-model-trainer:1.0.0
            image: akramdocke/mlip-model-trainer:1.0.0
            imagePullPolicy: Always
            volumeMounts:
            - name: model-volume
              mountPath: /shared-volume
          volumes:
          - name: model-volume
            persistentVolumeClaim:
              claimName: model-pvc
          terminationGracePeriodSeconds: 30
          restartPolicy: OnFailure              